version: '3'
services:
  mysql:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_DATABASE=test
    volumes:
      - 'db:/var/lib/mysql'
volumes:
  db:
